name: CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Compile and test (Windows)
        if: runner.os == 'Windows'
        run: .\gradlew.bat check demoClasses
      - name: Compile and test (Linux)
        if: runner.os == 'Linux'
        run: ./gradlew check demoClasses
